env:
  browser: true
  es2021: true
root: true
extends:
  - '@gabrielyotoo/eslint-config-react-native'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./packages/*/tsconfig.json
rules:
  no-console: error
  curly: error
  radix: error
  no-multiple-empty-lines: error
  no-new-wrappers: error
  semi: error
settings:
  react:
    createClass: createReactClass
    pragma: React
    fragment: Fragment
    version: detect
